title: Yurlak's Blog
author:
  name: YURLAK
  email: 1254316639@qq.com
description: Hello!!!

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  skin: auto
  # generate social links in footer
  social_links:
    - { platform: github,         user_url: "https://github.com/jekyll/minima" }
    - { platform: telegram,       user_url: "https://t.me/YURLAK" }
    - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

navbar-links:
  Home: "https://YURLAK.github.io"

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
